Allow starting the CLI with an initial pwd set
use-ink/drink pull request #23
Opened 2023-07-05 13:48 UTC by piotrMocz

This was mentioned as a half-measure for #8 and it seems to cover a lot of the use cases (assuming users start `drink-cli` to mostly work on one contract.

Usage:
```
$ drink-cli --help
Usage: drink-cli [OPTIONS]

Options:
  -p, --path <DIRECTORY>  Starts the CLI in the provided directory
  -h, --help              Print help
  -V, --version           Print version
```

So you're able to start it like:
```
$ drink-cli examples/flipper
```
And immediately call `build`.

2023-07-05 15:16 UTC, pmikolajczyk41 requested changes
when I run: `cargo run --release -- -p /home/<my local path>/drink/examples/flipper`, optionally build the contract and try to deploy it, I get error about finding contract file

this helps:
```rust
fn find_wasm_blob(pwd: &PathBuf) -> Option<(String, PathBuf)> {
    let Ok(entries) = fs::read_dir(pwd.join("target/ink")) else {
```

2023-07-05 15:16 UTC, pmikolajczyk41 commented on drink-cli/src/app_state/mod.rs
> +            ..Default::default()
in order to deduplicate a bit, I would specify here the rest of the arguments and in the `default` implementation I would put `Self::new(None)`

2023-07-06 15:24 UTC, piotrMocz commented on drink-cli/src/app_state/mod.rs
> +            ..Default::default()
Yeah that's actually a way more natural order of dependencies (i.e. the constructor doesn't assume the existence of the `Default` impl, which kind of seemed like an anti-pattern anyway... Thanks!

2023-07-06 15:26 UTC, pmikolajczyk41 approved these changes

2023-07-06 15:31 UTC, merged